# _config.alog.yml
menu:
  - name: Home
    path: /
  - name: Projects
    path: /projects
  - name: Message
    path: /message
  - name: Links
    path: /links
  - name: About
    path: /about

links:
  site_info:
    name: Alog
    link: https://akino.icu
    icon: https://akino.icu/images/avatar.jpg
  apply_tips: Apply format:\nName：xxxx\ndesc:xxx\nLink：xxx\nIcon：xxx
  link_list:
    - name: Akino
      avatar: /images/avatar.jpg
      link: https://akino.icu
      desc: Akino's blog.

# 页脚
footer:
  enable: true
  building_time: 2023 # 建站时间
  descr: # 随便写点话吧！

# 开启页面加载动画
loading:
  enable: true

# 开启文章阅读次数统计
busuanzi:
  enable: true

comments:
  use: # valine | waline | twikoo
  valine:
    appId: # your app id
    appKey: # your app key
    avatar: # avatar style
    placeholder: xxx # 评论输入框占位文字
    pageSize: 10 # 评论列表每一页的评论数量
    visitor: false # 文章阅读次数统计
    recordIP: true
  waline:
    serverURL: # 部署的url
  twikoo:
    envId: # 腾讯云部署填写envId，vercel部署填写服务器地址
    region: ap-shanghai # 默认为ap-shanghai

# 本地搜索依赖hexo-generator-searchdb，在使用前请先安装该依赖
local_search:
  enable: true
  top_n_per_article: 1 # 每篇文章显示的搜索匹配数量
  preload: true # 预加载数据
  trigger: auto